"""add passphrase_hash

Revision ID: 7b4138ee8d4e
Revises: 32a8792b3c36
Create Date: 2025-04-12 02:04:29.874857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4138ee8d4e'
down_revision: Union[str, None] = '32a8792b3c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('passphrase_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret', 'passphrase_hash')
    # ### end Alembic commands ###
